/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_doomgame_free: (a: number, b: number) => void;
export const doomgame_alive_enemies: (a: number) => number;
export const doomgame_current_tick: (a: number) => bigint;
export const doomgame_current_weapon: (a: number) => number;
export const doomgame_game_over: (a: number) => number;
export const doomgame_has_blue_key: (a: number) => number;
export const doomgame_has_chaingun: (a: number) => number;
export const doomgame_has_red_key: (a: number) => number;
export const doomgame_has_rocket_launcher: (a: number) => number;
export const doomgame_has_shotgun: (a: number) => number;
export const doomgame_is_title_screen: (a: number) => number;
export const doomgame_level_complete: (a: number) => number;
export const doomgame_new: () => number;
export const doomgame_player_alive: (a: number) => number;
export const doomgame_player_ammo: (a: number) => number;
export const doomgame_player_angle: (a: number) => number;
export const doomgame_player_armor: (a: number) => number;
export const doomgame_player_health: (a: number) => number;
export const doomgame_player_kills: (a: number) => number;
export const doomgame_player_rockets: (a: number) => number;
export const doomgame_player_shells: (a: number) => number;
export const doomgame_player_x: (a: number) => number;
export const doomgame_player_y: (a: number) => number;
export const doomgame_projectile_count: (a: number) => number;
export const doomgame_render: (a: number) => void;
export const doomgame_reset: (a: number) => void;
export const doomgame_rgba_len: (a: number) => number;
export const doomgame_rgba_ptr: (a: number) => number;
export const doomgame_screen_height: (a: number) => number;
export const doomgame_screen_width: (a: number) => number;
export const doomgame_start_game: (a: number) => void;
export const doomgame_tick: (a: number, b: number, c: number) => void;
export const doomgame_total_enemies: (a: number) => number;
export const render_from_scale: (a: number, b: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
